import ExpoHaptics from './ExpoHaptics';

/**
 * Notification Feedback Type
 * The type of notification feedback generated by a UINotificationFeedbackGenerator object.
 * https://developer.apple.com/documentation/uikit/uinotificationfeedbacktype
 */
export enum NotificationFeedbackType {
  /**
   * A notification feedback type indicating that a task has completed successfully
   */
  Success = 'success',
  /**
   * A notification feedback type indicating that a task has produced a warning
   */
  Warning = 'warning',
  /**
   * A notification feedback type indicating that a task has failed
   */
  Error = 'error',
}

/**
 * Impact Feedback Style
 * The mass of the objects in the collision simulated by a UIImpactFeedbackGenerator object.
 * https://developer.apple.com/documentation/uikit/uiimpactfeedbackstyle
 */
export enum ImpactFeedbackStyle {
  /**
   * A collision between small, light user interface elements
   */
  Light = 'light',
  /**
   * A collision between moderately sized user interface elements
   */
  Medium = 'medium',
  /**
   * A collision between large, heavy user interface elements
   */
  Heavy = 'heavy',
}

export function notification(type: NotificationFeedbackType = NotificationFeedbackType.Success): Promise<null> {
  console.warn('Haptics.notification is deprecated. Use Haptics.notificationAsync instead.');
  return notificationAsync(type);
}

export function impact(style: ImpactFeedbackStyle = ImpactFeedbackStyle.Medium): Promise<null> {
  console.warn('Haptics.impact is deprecated. Use Haptics.impactAsync instead.');
  return impactAsync(style);
}

export function selection(): Promise<null> {
  console.warn('Haptics.selection is deprecated. Use Haptics.selectionAsync instead.');
  return selectionAsync();
}

/**
 * Triggers notification feedback.
 */
export async function notificationAsync(type: NotificationFeedbackType = NotificationFeedbackType.Success): Promise<null> {
  return ExpoHaptics.notificationAsync(type);
}

/**
 * Triggers impact feedback.
 */
export async function impactAsync(style: ImpactFeedbackStyle = ImpactFeedbackStyle.Medium): Promise<null> {
  return ExpoHaptics.impactAsync(style);
}

/**
 * Triggers selection feedback.
 */
export async function selectionAsync(): Promise<null> {
  return ExpoHaptics.selectionAsync();
}
